# Generated by Django 4.2.13 on 2024-10-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_auto_20190124_2058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alphagramtag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lexicon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="maintenance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedlist",
            name="category",
            field=models.CharField(
                choices=[
                    ("A", "Anagram"),
                    ("B", "Build"),
                    ("T", "Through"),
                    ("Y", "Typing"),
                ],
                default="A",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="savedlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
