# Generated by Django 2.2.2 on 2019-08-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190124_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerolithprofile',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
