# Generated by Django 4.2.13 on 2024-10-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20190124_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="aerolithprofile",
            name="wordvault_settings",
            field=models.TextField(blank=True, default="{}"),
        ),
        migrations.AlterField(
            model_name="aerolithprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
